-- Your SQL goes here
ALTER TABLE meals
ADD COLUMN prep_time VARCHAR NOT NULL DEFAULT '0 minutes',
ADD COLUMN servings INTEGER NOT NULL DEFAULT 1 CHECK (servings > 0),
ADD COLUMN calories VARCHAR NOT NULL DEFAULT '0 kcal',
ADD COLUMN protein VARCHAR NOT NULL DEFAULT '0g',
ADD COLUMN fat VARCHAR NOT NULL DEFAULT '0g',
ADD COLUMN carbs VARCHAR NOT NULL DEFAULT '0g',
ADD COLUMN difficulty VARCHAR NOT NULL DEFAULT 'Easy';