@baseUrl = https://w4ocw8og004448w444ogws8w.coolify.agnieve.pro
@authToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjE3Mzk5MzU4ODB9.PflCZDAKUmsUsmtU4zgvzkz0YPS3CWH8w4kdun9ud8Q

### Get all body parts
GET {{baseUrl}}/body-parts
Authorization: Bearer {{authToken}}

### Get single body part
GET {{baseUrl}}/body-parts/1
Authorization: Bearer {{authToken}}

### Create body part
POST {{baseUrl}}/body-parts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Chest",
    "description": "Chest muscles including pectoralis major and minor"
}

### Update body part
PATCH {{baseUrl}}/body-parts/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Updated Chest",
    "description": "Updated description for chest muscles"
}

### Delete body part
DELETE {{baseUrl}}/body-parts/1
Authorization: Bearer {{authToken}}