@baseUrl = https://q8swckkcso4k80osog8sg840.coolify.agnieve.com
# @baseUrl = http://localhost:3000
@authToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjIwNjAzNDAxOTR9.2KsuOn2AKp1uMsrnrYJN-nJMXJqXLfgKOvGSCUCW7D8

### Get all body parts
GET {{baseUrl}}/body-parts
Authorization: Bearer {{authToken}}

### Get single body part
GET {{baseUrl}}/body-parts/1
Authorization: Bearer {{authToken}}

### Create body part
POST {{baseUrl}}/body-parts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Chest",
    "description": "Chest muscles including pectoralis major and minor"
}

### Update body part
PATCH {{baseUrl}}/body-parts/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Updated Chest",
    "description": "Updated description for chest muscles"
}

### Delete body part
DELETE {{baseUrl}}/body-parts/1
Authorization: Bearer {{authToken}}