@baseUrl = http://localhost:8000
@authToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjE3Mzk4Njg0Mzh9.x-UydMPT73ZZXcIZJ261w9TaSyFXPq48_T9ou3PRu_s

### Get all categories
GET {{baseUrl}}/categories
Authorization: Bearer {{authToken}}

### Get single category
GET {{baseUrl}}/categories/1
Authorization: Bearer {{authToken}}

### Create category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Strength Training",
}

### Update category
PATCH {{baseUrl}}/categories/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Updated Strength Training",
    "description": "Updated description for strength training exercises"
}

### Delete category
DELETE {{baseUrl}}/categories/1
Authorization: Bearer {{authToken}}