@baseUrl = http://localhost:3000
# @baseUrl = https://w4ocw8og004448w444ogws8w.coolify.agnieve.pro
@authToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjQiLCJleHAiOjE3NDAyNDY3NTl9.FsibSIa_LSWC48bZyK8sr5gLOw1qjgwjw8JUqQSY8tA

### Add meal to favorites
POST {{baseUrl}}/favorite-meals
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "user_id": 1,
    "meal_id": 1
}

### Get user's favorite meals
GET {{baseUrl}}/favorite-meals/user/1
Authorization: Bearer {{authToken}}

### Remove meal from favorites
DELETE {{baseUrl}}/favorite-meals/1
Authorization: Bearer {{authToken}}