@baseUrl = http://localhost:3000
@email = dev@agnieve.com
@newPassword = pass123
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjIwNTY1OTg0MTd9.O3qELMtaBPqwCd58vOB6Y_1EUYNQ4vorJG9aTM9wrXM

### Request password reset (sends email with reset token)
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
    "email": "{{email}}"
}

### Reset password with token
# Note: Replace <token> with the actual token received in email
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYXNzd29yZF9yZXNldCIsImVtYWlsIjoiZGV2QGFnbmlldmUuY29tIiwiZXhwIjoxNzQxMTA4MDgwfQ.TcitLqqiu82nhUNN5JugpmMLTkcS8NeQd_jsulnP4go",
    "new_password": "newpass123"
}

### Auto Reset Password (Authenticated)
POST {{baseUrl}}/me/auto-reset-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "current_password": "newpass123",
    "new_password": "{{newPassword}}"
}