@baseUrl = http://localhost:3000
# @baseUrl = https://w4ocw8og004448w444ogws8w.coolify.agnieve.pro

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjQiLCJleHAiOjIwNTU5MDE5MTV9.zYlmSXnmAEclLOz47-xeA7XGZOBCM9DlZjS44-TW0LY

### Login to get token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "dev@agnieve.com",
    "password": "pass123"
}

### Reset Password
POST {{baseUrl}}/users/me/reset-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "current_password": "newpass123",
    "new_password": "pass123"
}

### Update User Information
PATCH {{baseUrl}}/me/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "John Doe",
}

# pub name: Option<String>,
# pub email: Option<String>,
# pub password: Option<String>,
# pub profile_picture: Option<String>,
# pub role: Option<String>,
# pub status: Option<String>,