@baseUrl = https://q8swckkcso4k80osog8sg840.coolify.agnieve.com
# @baseUrl = https://w4ocw8og004448w444ogws8w.coolify.agnieve.pro

@authToken =  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjMiLCJleHAiOjIwNjAzNDAzNDh9.A-5vwB7LphQ1CzVmwQZYlUIKPot_f1zMUz4kt8ZapsI

### Me (Default Auth)
GET {{baseUrl}}/users/auth/me
Authorization: Bearer {{authToken}}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

### Get single user
GET {{baseUrl}}/users/1
Authorization: Bearer {{authToken}}

### Create user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Admin",
    "email": "admin@vpaaustralia.com",
    "password": "pass123",
    "role": "admin",
    "status": "active"
}

### Update user
PUT {{baseUrl}}/users/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "role": "admin"
}

### Delete user
DELETE {{baseUrl}}/users/2
Authorization: Bearer {{authToken}}