@baseUrl = http://localhost:3000
# @baseUrl = https://w4ocw8og004448w444ogws8w.coolify.agnieve.pro

@authToken =  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjQiLCJleHAiOjE3NDAyNDQ4MzR9.2nMMtFSYCRR8HNqmLiSkpXXa2eMaHRFJV0cN0qmoF2Q

### Me (Default Auth)
GET {{baseUrl}}/users/auth/me
Authorization: Bearer {{authToken}}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

### Get single user
GET {{baseUrl}}/users/1
Authorization: Bearer {{authToken}}

### Create user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "John",
    "email": "john@example.com",
    "password": "pass123",
    "role": "user",
    "status": "active"
}

### Update user
PUT {{baseUrl}}/users/2
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "role": "admin"
}

### Delete user
DELETE {{baseUrl}}/users/2
Authorization: Bearer {{authToken}}